apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev
spec:
  replicas: 5
  selector:
    matchLabels:
      app: dev
  template:
    metadata:
      labels:
        app: dev
    spec:
      containers:
      - args:
        - sleep
        - "3600"
        image: busybox
        name: main
