kind: Pod
apiVersion: v1
metadata:
  name: mongodb-pod
spec:
  containers:
  - name: mongodb
    image: mongo
    volumeMounts:
    - mountPath: "/data/db"
      name: mongodb-data
  volumes:
  - name: mongodb-data
    persistentVolumeClaim:
      claimName: mongodb-pvc